version: '2'
services:

  chrome:
    image: selenium/node-chrome:3.141
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.141
    ports:
      - "4444:4444"

  schedule:
    image: binschedule:latest
    ports:
      - "8080:8080"
